# Generated by Django 4.2.11 on 2024-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triggerlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='trigger_headline',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trigger',
            name='trigger_date',
            field=models.IntegerField(choices=[(0, 'Pick a year and quarter'), (1, '2024-Q1'), (2, '2024-Q2'), (3, '2024-Q3'), (4, '2024-Q4'), (5, '2024-H1'), (6, '2024-H2'), (7, '2025-Q1'), (8, '2025-Q2'), (9, '2025-Q3'), (10, '2025-Q4'), (11, '2025-H1'), (12, '2025-H2')], default=0),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='website_link',
            field=models.CharField(max_length=200),
        ),
    ]
