# Generated by Django 4.2.11 on 2024-03-18 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triggerlist', '0002_trigger_trigger_headline_alter_trigger_trigger_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
